name: Apps

on:
  push:
    branches:
      - release
    paths:
      - .github/workflows/apps*
      - apps/**

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install Hal9
      run: pip install hal9
    - name: Deploy Echo
      run: hal9 deploy apps/echo --name ECHO --access public --title Echo --description "Echoes user input"
      env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
    - name: Deploy Hal9
      run: hal9 deploy apps/hal9 --name hal9 --access public --title Hal9 --description "Conversations and content creation"
      env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
    - name: Deploy Flux
      run: hal9 deploy apps/flux --name flux --access public --title Flux --description "Photorealistic content creation"
      env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
    - name: Deploy Browser
      run: hal9 deploy apps/browser --name browser --access unlisted --title Browser --description "Capable of browsing the web"
      env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
    - name: Deploy OpenAI
      run: hal9 deploy apps/openai --name openai --access public --title OpenAI --description "Makes use of OpenAI O1"
      env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}