name: JavaScript

on:
  push:
    paths:
      - javascript/**
      - .github/workflows/javascript.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@hal9ai'
      - run: yarn install
        working-directory: ./javascript
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
