name: Client

on:
  push:
    paths:
      - js/**
      - .github/workflows/js.yaml

jobs:
  npm:
    runs-on: ubuntu-latest
    env:
      HAL9_ENV: prod
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@hal9ai'
      - run: yarn install
        working-directory: ./js
      - run: yarn build:npm
        working-directory: ./js
      - run: npm publish
        working-directory: ./js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.ref == 'refs/heads/main'