name: Website

on:
  push:
    paths:
      - website/**
      - .github/workflows/website.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
        working-directory: website
      - run: yarn prebuild
        working-directory: website
      - run: yarn build
        working-directory: website
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
