name: Website

on:
  push:
    paths:
      - website/**
      - .github/workflows/website.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: yarn
        working-directory: website
      - run: yarn docusaurus deploy
        working-directory: website
